# Generated by Django 2.2 on 2020-05-19 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
