# Generated by Django 2.2 on 2020-05-21 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200519_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='评论内容', verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, help_text='被评论文章', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.Post', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='发表时间', verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=1, help_text='被赞文章', on_delete=django.db.models.deletion.CASCADE, to='post.Post', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='like',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='点赞时间', verbose_name='发表时间'),
        ),
    ]
