# Generated by Django 2.2 on 2020-05-21 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200521_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞者'),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=1, help_text='被赞文章', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.Post', verbose_name='文章'),
        ),
    ]
