# Generated by Django 2.2 on 2020-05-27 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20200521_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_comment',
            field=models.ForeignKey(blank=True, help_text='父级评论', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.Comment'),
        ),
    ]
