# Generated by Django 2.2 on 2020-06-11 15:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20200527_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='评论内容', verbose_name='评论内容'),
        ),
    ]
