# Generated by Django 2.2 on 2020-05-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200526_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数'),
        ),
    ]
