# Generated by Django 2.2 on 2020-05-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_like_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='read_num',
            field=models.IntegerField(default=0, help_text='阅读量', verbose_name='阅读量'),
        ),
    ]
