# Generated by Django 2.2 on 2020-05-27 08:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200527_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='文章内容', verbose_name='文章内容'),
        ),
    ]
