# Generated by Django 2.2 on 2020-06-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='default title', help_text='博文标题', max_length=200, verbose_name='文章标题'),
        ),
    ]
