# Generated by Django 2.2 on 2020-06-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200603_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, help_text='上传文件', null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='上传图片', null=True, upload_to='upload'),
        ),
    ]
