# Generated by Django 2.2 on 2020-05-26 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200526_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='注册时间', verbose_name='注册时间'),
        ),
    ]
