# Generated by Django 2.2 on 2020-06-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head',
            field=models.ImageField(blank=True, help_text='头像', null=True, upload_to='upload', verbose_name='头像'),
        ),
    ]
