# Generated by Django 2.2 on 2020-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.IntegerField(default=0, help_text='粉丝数', verbose_name='粉丝数'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriber',
            field=models.IntegerField(default=0, help_text='已关注数', verbose_name='已关注数'),
        ),
    ]
