# Generated by Django 2.2 on 2020-06-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200609_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='1@1.com', max_length=254, unique=True, verbose_name='邮箱'),
        ),
    ]
