# Generated by Django 2.2 on 2020-06-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200612_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='默认用户名', max_length=200, unique=True, verbose_name='用户名'),
        ),
    ]
