# Generated by Django 2.2 on 2020-06-08 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0012_auto_20200608_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='上传文件', null=True, upload_to='upload')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='点赞时间', verbose_name='发表时间')),
                ('author', models.ForeignKey(default=1, help_text='上传人', on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('post', models.ForeignKey(default=1, help_text='博文', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='post.Post', verbose_name='文章')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
