# Generated by Django 2.2 on 2020-06-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='post',
            field=models.ForeignKey(blank=True, default=1, help_text='博文', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='post.Post', verbose_name='文章'),
        ),
    ]
